version: '3'

services:
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "BLABLABLA"
      RABBITMQ_DEFAULT_VHOST: "/"

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass

  arango:
      image: arangodb/arangodb
      environment:
        ARANGO_ROOT_PASSWORD: pass

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  web_server:
    build: .
    links:
        - "rabbitmq"
        - "redis:redisDocker"
        - "arango"
        - "postgresdb"
    command:  bash -c "sleep 10; java -cp target/Pinterest-1.0-SNAPSHOT-jar-with-dependencies.jar RunBackEnd server"
    depends_on:
      - rabbitmq
      - postgresdb
      - arango
      - redis
    ports:
      - "8080:8080"

  controller:
    build: .
    links:
        - "rabbitmq"
        - "redis:redisDocker"
        - "arango"
        - "postgresdb"
    command:  bash -c "java -cp target/Pinterest-1.0-SNAPSHOT-jar-with-dependencies.jar RunBackEnd controller"
    depends_on:
      - rabbitmq
      - postgresdb
      - arango
      - redis


  load_balancer:
    build: .
    links:
        - "rabbitmq"
        - "redis:redisDocker"
        - "arango"
        - "postgresdb"
    command:  bash -c "sleep 10; java -cp target/Pinterest-1.0-SNAPSHOT-jar-with-dependencies.jar RunBackEnd loadBalancer"
    depends_on:
      - rabbitmq
      - postgresdb
      - arango
      - redis

  mq_instance:
    build: .
    links:
        - "rabbitmq"
        - "redis:redisDocker"
        - "arango"
        - "postgresdb"
    command:  bash -c "sleep 10; java -cp target/Pinterest-1.0-SNAPSHOT-jar-with-dependencies.jar RunBackEnd mQinstance"
    depends_on:
      - rabbitmq
      - postgresdb
      - arango
      - redis

  service:
    build: .
    links:
        - "controller"
        - "rabbitmq"
        - "redis:redisDocker"
        - "arango"
        - "postgresdb"
    command:  bash -c "sleep 10; java -cp target/Pinterest-1.0-SNAPSHOT-jar-with-dependencies.jar RunBackEnd client post"
    depends_on:
      - controller
      - rabbitmq
      - postgresdb
      - arango
      - redis

volumes:
  redis-data:
